### PR TITLE
Add FAQ page

### PR DESCRIPTION
**Pull request by Folyd**

### CODE REVIEW

**Comment by pau1tuck** [comment]
It's starting to take shape really nicely @Folyd.
Maybe everyone in the editorial team could quickly introduce themselves so we know each other a bit better?

**Review by pau1tuck — APPROVED** [review]

**Comment by Folyd** [comment]
> It's starting to take shape really nicely @Folyd. Maybe everyone in the editorial team could quickly introduce themselves so we know each other a bit better?

BTW, do we need a Discord channel to discuss this? Or maybe some magazine operation things?

**Comment by LCrossman** [comment]
Discord could be good plan

**Comment by pau1tuck** [comment]
Sounds like a good way to stay in touch, if everyone else is okay with it.

**Pull request merged**
