### PR TITLE
Article: Pursuit of Performance on Building a JavaScript Compiler

### PR DESCRIPTION
**Pull request by Boshen**
This is the initial draft for my article.

### CODE REVIEW

**Comment by Boshen** [comment]
I changed the title from linter to parser.
 
I also started dumping words into the article, this may become very long ...

**Comment by Boshen** [comment]
@Folyd Can you give me 👍 or 👎 if the direction I'm going is ok, and is the first person story telling tone ok?

**Comment by Folyd** [comment]
Hi, @Boshen. Thanks for asking. Feel free to change the article style or content. 👍

**Comment by Boshen** [comment]
Ready for review.

**Review by Folyd — APPROVED** [review]

**Pull request merged**
