### PR TITLE
New article: How to distribute your Rust binary to multiple Operating Systems with Github Actions

### PR DESCRIPTION
**Pull request by dmosc**

### CODE REVIEW

**Review by pau1tuck — APPROVED** [review]

**Comment by MATRIXKOO** [comment]
LGTM

**Comment by LCrossman** [comment]
:thumbsup:

**Comment by Folyd** [comment]
I like this article, however, it is not informative enough. I hope all articles can be high-quality enough for the readers. Also, it has been merged by @MATRIXKOO who is not an editor team member, so I prefer to revert the merge, sorry. @dmosc

**Comment by MATRIXKOO** [comment]
Sorry，I mistook this repo as
a former repo. I don't know how I get merge auth.
Also, may I join your editor team?
Actually, I am member of former repo rust magazine 2021.

**Comment by Folyd** [comment]
Hi, @MATRIXKOO, never mind, and thanks for your asking. Unfortunately, we already got enough editors. Maybe later?  See: https://rustmagazine.org/about/#the-editorial-team

**Pull request merged**
